<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Application;
use AppBundle\Entity\Space;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    /**
     * @param User $owner
     *
     * @return array
     */
    public function getApplicationPerOwner(User $owner)
    {
        $qb = $this->createQueryBuilder('a')
            ->addSelect('space')
            ->addSelect('user')
            ->innerJoin('a.space','space')
            ->innerJoin('space.owner','user')
            ->where('space.owner = :user_id')
            ->setParameters(array(
                'user_id' => $owner->getId()
            ));

        return $qb->getQuery()->getResult();
    }

    public function filter($params)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a');

        if (!empty($params['space'])) {
            $qb->andWhere('a.space = :space')->setParameter('space',$params['space'] );
        }

        if (!empty($params['orderBy'])) {
            $qb->orderBy('a.'.$params['orderBy'], $params['sort']);
        }

        return $qb->getQuery()->getResult();
    }    
    
}
