security:
    encoders:
        AppBundle\Entity\User: sha512
    role_hierarchy:
        ROLE_OWNER :  [ROLE_USER]
        ROLE_PROJECT_HOLDER :  [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_PROJECT_OLDER, ROLE_OWNER]
        ROLE_SUPER_ADMIN: [ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
    providers:
        fos_userbundle:
            id: fos_user.user_manager


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:      /admin/
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                use_forward:    true
                use_referer: true
                check_path:     sonata_user_admin_security_check
                #failure_path:   null
            logout:
                path:           sonata_user_admin_security_logout
                target:         homepage
            anonymous:    true

        # defaut login area for standard users
        main:
            pattern:            ^/

            form_login:
                provider:       fos_userbundle
                login_path:     security_login_error
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                #failure_path:   null
                default_target_path: homepage

            oauth:
                provider: fos_userbundle

                failure_path: security_login_error
                login_path: /
                # login_path: /
                # check_path: /connexion

                failure_path: /
                # login_path: /connexion
                # login_path: security_login_error

                # check_path: fos_user_security_check

                resource_owners:
                    facebook: "/connect/check-facebook"

                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

                default_target_path: homepage

            logout:
                path: fos_user_security_logout
                target: homepage

            anonymous:    true


    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/espace-manager/, roles: ROLE_OWNER }
        - { path: ^/espaces/, roles: ROLE_USER }
        - { path: ^/recherche/, roles: ROLE_USER }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profil, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/deconnexion$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
