security:
    encoders:
        AppBundle\Entity\User: sha512
    role_hierarchy:
        ROLE_OWNER :  [ROLE_USER]
        ROLE_PROJECT_HOLDER :  [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_PROJECT_HOLDER, ROLE_OWNER]
        ROLE_SUPER_ADMIN: [ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            #id: fos_user.user_manager # pour fos_userbundle 1.3.x


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            logout_on_user_change: true
            pattern:      /admin/
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                use_forward:    true
                use_referer: true
                check_path:     sonata_user_admin_security_check
                #failure_path:   null
            logout:
                path:           sonata_user_admin_security_logout
                target:         homepage
            anonymous:    true

        # defaut login area for standard users
        main:
            pattern:            ^/

            form_login:
                provider:       fos_userbundle
                login_path:     security_login_error
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                #failure_path:   null
                default_target_path: homepage

            logout:
                path: fos_user_security_logout
                target: homepage

            anonymous:    true
            logout_on_user_change: true


    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/espace-manager/, roles: ROLE_OWNER }
        - { path: ^/appels-a-candidature/, roles: ROLE_OWNER }
        - { path: ^/espaces/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mes-candidatures, roles: ROLE_USER }
        - { path: ^/recherche/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profil, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/deconnexion$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
