services:
    app.admin.users.admin.owners:
        class: AppBundle\Admin\OwnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Propriétés, label: Propriétaires }
        arguments:
            - ~
            - AppBundle\Entity\User
            -

    app.admin.users.admin.project_holder:
        class: AppBundle\Admin\ProjectHolderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Candidatures, label: Les porteurs de projet}
        arguments:
            - ~
            - AppBundle\Entity\User
            -

    app.admin.spaces:
        class: AppBundle\Admin\SpaceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Propriétés, label: Propriétés }
        arguments:
            - ~
            - AppBundle\Entity\Space
            -

    app.admin.spaces.attributes:
        class: AppBundle\Admin\AttributeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Propriétés, label: Attributs de propriété }
        arguments:
            - ~
            - AppBundle\Entity\Attribute
            -

    app.admin.spaces.images:
        class: AppBundle\Admin\SpaceImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Propriétés, label: images de propriété , show_in_dashboard: false  }
        arguments:
            - ~
            - AppBundle\Entity\SpaceImage
            -

    app.admin.spaces.parcel:
        class: AppBundle\Admin\ParcelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Propriétés, label: lot de propriété , show_in_dashboard: true  }
        arguments:
            - ~
            - AppBundle\Entity\Parcel
            -

    app.form.type.space:
        class: AppBundle\Form\SpaceType
        tags:
            - { name: form.type, alias: appbundle_space }

    app.admin.image_admin_type:
         class: AppBundle\Form\ImageAdminType
         tags:
             - { name: form.type, alias: image_admin_type }
